spring:
  application:
    name: account-system-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
server:
  port: 9001
dubbo:
  application:
    name: account-system-api
    id: account-system-api
  registry:
    address: spring-cloud://localhost
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    base-packages: com.zx.account.system
  cloud:
    subscribed-services: account-system-order
