spring:
  application:
    name: account-system-member

server:
  port: 9002

dubbo:
  application:
    name: account-system-member-dubbo
  registry:
    address: nacos://8.130.181.162:8848/
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.zx.account.system.member.service.impl

